import streamlit as st
import os
from .SVDppVisualizationRenderer import SVDppVisualizationRenderer

class ASVDVisualizationRenderer(SVDppVisualizationRenderer):
    """
    Renders visualizations specific to Asymmetric SVD.
    It inherits from SVDpp renderer as the plot types are identical
    (Objective, Factor Change, Snapshots), but the interpretation
    of the 'P' matrix in the snapshot is different.
    """
    def __init__(self, run_dir, explanations):
        """Initialize the renderer."""
        super().__init__(run_dir, explanations) # Call parent __init__
        self.algorithm_name = "ASVD" # Set correct name

        # Update explanations for ASVD
        self.explanations.update({
            "Objective": "Shows the Root Mean Squared Error (RMSE) calculated on the "
                         "*observed ratings* in the training set over iterations. "
                         "A decreasing trend indicates convergence.",
            "Factor Change": "Shows the Frobenius norm of the change in the item (Q), "
                             "explicit item (X), and implicit item (Y) latent factor "
                             "matrices between iterations. A decreasing trend "
                             "indicates convergence.",
            "Snapshots": "These plots visualize the distributions and relationships "
                         "within the latent factor matrices at key iterations.\n\n"
                         "* **P (Heatmap):** This shows the **Explicit Item Factors (X)**.\n"
                         "* **Q (Heatmap):** This shows the primary **Item Factors (Q)**.\n"
                         "* **Y (Heatmap):** This shows the **Implicit Item Factors (Y)**."
        })

    # The render() method is inherited from SVDppVisualizationRenderer
    # and will automatically find and render the 'factor_snapshot'
    # and 'line_plot' entries generated by ASVDVisualizer.